### ISSUE TITLE
Sort out local schema location

### ISSUE THREAD

**Issue by hcayless** [TEIC/oxgarage#21]
The TEI Debian packages have a standard location where they put everything, including Exemplar schemas. But people who run oxgarage on other OSes will need to be able to configure their own locations. There's a validators.xml file buried in ege-validators, but we might want to think about a more generalized config option. The same goes for the Stylesheets, actually.

**Comment by peterstadler** [comment]
Since OxGarage and TEIGarage are dockerized the preferred approach is now to mount your local schemas etc into the container, see https://github.com/TEIC/TEIGarage/#tei-sources-and-stylesheets

I'm closing the issue since we're going to archive this repo anyway but please feel free to (re)open this issue at https://github.com/TEIC/TEIGarage/issues
