### ISSUE TITLE
ODD to RNC returns a zip file

### ISSUE THREAD

**Issue by raffazizzi** [TEIC/oxgarage#45]
I would expect a simple RelaxNG Compact file, but instead this transformation returns a zip file containing an RNC document and a hidden file that seems to be the XML syntax RNG file.

**Comment by anneferger** [comment]
After discussing this with @peterstadler this seems to happen only if an additional nfs volume is used in the OxGarage Setup - the temp file is not deleted correctly after then and thus put into the zip file, this needs to be fixed in the TEIGarage-Code (Note to me: probably in https://github.com/TEIC/tei-converter/blob/865e74cbc64c18a543083d3ceb49eb21506b2f73/src/main/java/pl/psnc/dl/ege/tei/TEIConverter.java#L588), but in the new setup it will not be a problem, since (at first) no other volumes will be used/mounted

**Comment by peterstadler** [comment]
Should be fixed in the OxGarage successor https://github.com/TEIC/teigarage. If the issue reappears, please file a ticket there

NB, the deployment at teigarage.tei-c.org is not yet updated but will be in the next days
